# Generated by Django 3.1.7 on 2021-04-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='override_desc',
            field=models.TextField(blank=True, help_text='The description or summary of the post. Overrides the auto-fetched description.', null=True),
        ),
    ]
