# Generated by Django 3.1.7 on 2021-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20210412_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='override_pub',
            field=models.DateTimeField(help_text='The publication date/time of the post. Overrides the auto-fetched date/time.', null=True),
        ),
    ]
