# Generated by Django 3.1.7 on 2023-01-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_post_override_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='override_pub',
            field=models.DateTimeField(blank=True, help_text='The publication date/time of the post. Overrides the auto-fetched date/time.', null=True),
        ),
        migrations.CreateModel(
            name='PollError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_time', models.DateTimeField(auto_now_add=True, help_text='The date/time at which the error was recorded.')),
                ('error_summary', models.CharField(help_text='A summary of the error.', max_length=1024)),
                ('error_code', models.BigIntegerField(help_text='Any error code associated with the error.')),
                ('error_message', models.TextField(help_text='The details of the error.')),
                ('in_feed', models.ForeignKey(help_text='The inbound found from where the post originated.', on_delete=django.db.models.deletion.CASCADE, to='feeds.infeed')),
            ],
        ),
    ]
